### ISSUE TITLE
Text opacity/brightness not editable

### ISSUE THREAD

**Issue by SickNova** [MeineZ/BMSessionPlugin#14]
This is not an issue. The plugin is exactly what I was looking for: minimal infos with minimal design.
The only problem is that sometimes is quit unreadable. It would be perfect if I could set the text color opacity/brightness for a better readability.
Thank you!

**Comment by MeineZ** [comment]
I appreciate your comments! Thanks a lot!

I believe you are already able to set the opacity.. I'll check it out within the next 24 hours :) 

Brightness is not a thing for fonts within BakkesMod, so you'll have to do with opacity.. For now that is :D

**Comment by The-XPer** [comment]
I had the same problem, just didn't understand where/how to change the opacity. I didn't realise that it was a choice marked A in the colour selections. also it goes from 0-? which is kinda weird for someone like me who has no idea what any of it actually means. Apart from the slight unintuitive problem above its a great plugin 10/10.

**Comment by MeineZ** [comment]
The opacity can be changed in the most right input field in the color-window that pops up when clicking one of the colors (see attached image).

Every single number in these fields goes from 0 - 255. Where, in the case of opacity, 0 is completely transparent (invisible) and 255 is not.
Below those fields is the hexadecimal format for a color, the last two characters (4B in the attached image) are for opacity. If you know, you know, otherwise use the "A:" input field above.

![image](https://user-images.githubusercontent.com/18393968/198248328-49c6d4ff-56b2-4ebb-b11f-b24592fe1b9b.png)

**Comment by SickNova** [comment]
Thank you guys for your rapid response. After @The-XPer comment I tried to change that value and it worked.
Honestly I didn't know that the A value was for the opacity.
Thanks for the support and again congratulations for the plugin, I'm closing the issue.
