### ISSUE TITLE
Unable to edit any options

### ISSUE THREAD

**Issue by tocsikc** [MeineZ/BMSessionPlugin#17]
Recently reinstalled the plugin and now I have no options to configure (mainly need to change the position)
![image](https://github.com/MeineZ/BMSessionPlugin/assets/131706771/c1c4b6c9-10e1-49a6-a364-3d5082ddeaeb)

**Comment by MeineZ** [comment]
Hey, thank you for reaching out!
This could have several reasons. Let me ask you first; What do you mean with 'reinstalled'? What steps did you take for doing that?

**Comment by tocsikc** [comment]
Oh I mean by a fresh install of RL

**Comment by MeineZ** [comment]
Hmmm, it has been a while since I worked on BakkesMod plugins.

1) You can try to disable and then enable the plugin in the "Plugin Manager (Beta)" window. See if that works. I'm not sure about some of the troubleshooting actions anymore, but enabling and disabling the plugin may work already.
2) Otherwise, you can try to disable the plugin via the  "Plugin Manager (Beta)", restart Rocket League, and enable it again.
3) If that doesn't work, try disabling the plugin, close RL, install the plugin again from [here](https://bakkesplugins.com/plugins/view/151), and start rocketleague again.
4) Otherwise, it may be a mismatching version perhaps. Most likely the names of the plugin and its settings file don't match or something like that. But I don't recall the fix for that.

When none of the options above work out for you, I think you're best of just re-installing the plugin.
This requires some manual work though. If you're not sure how to do this, let me know, I could try to go back and see how to do this. Although, my time is limited at the moment.

**Comment by tocsikc** [comment]
I didn't even think of reopening the game, but I did and now it is all working, thanks for the help though.
